% Auto-generated by cameraCalibrator app on 01-Dec-2020
%-------------------------------------------------------


% Define images to process
imageFileNames = {'/home/driverless/Documents/MATLAB/Examples/R2020b/lidar/LidarCameraCalibrationExample/images/01.png',...
    '/home/driverless/Documents/MATLAB/Examples/R2020b/lidar/LidarCameraCalibrationExample/images/02.png',...
    '/home/driverless/Documents/MATLAB/Examples/R2020b/lidar/LidarCameraCalibrationExample/images/03.png',...
    '/home/driverless/Documents/MATLAB/Examples/R2020b/lidar/LidarCameraCalibrationExample/images/04.png',...
    '/home/driverless/Documents/MATLAB/Examples/R2020b/lidar/LidarCameraCalibrationExample/images/05.png',...
    '/home/driverless/Documents/MATLAB/Examples/R2020b/lidar/LidarCameraCalibrationExample/images/06.png',...
    '/home/driverless/Documents/MATLAB/Examples/R2020b/lidar/LidarCameraCalibrationExample/images/07.png',...
    '/home/driverless/Documents/MATLAB/Examples/R2020b/lidar/LidarCameraCalibrationExample/images/08.png',...
    '/home/driverless/Documents/MATLAB/Examples/R2020b/lidar/LidarCameraCalibrationExample/images/09.png',...
    '/home/driverless/Documents/MATLAB/Examples/R2020b/lidar/LidarCameraCalibrationExample/images/10.png',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 67;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
